"""empty message

Revision ID: 7f9653b246ca
Revises: 6de15d1a6c02
Create Date: 2017-07-24 20:41:30.847038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9653b246ca'
down_revision = '6de15d1a6c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('qq', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('qq', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'qq')
    op.drop_column('roles', 'qq')
    # ### end Alembic commands ###
